#!/usr/bin/env sh
type=$1
color=$2
icon=$3

info=$(curl -s https://api.coinmarketcap.com/v1/ticker/${type}/);
delta=$(tail -1 <<< $(grep -Po '[0-9\.\-\+]+' <<< $(grep _24h <<< ${info})));
price=$(grep -Po '[0-9\.]+' <<< $(grep price_usd <<< ${info}));
preformat=$([ $(cut -b 1 <<< ${delta}) == '-' ] && echo '%{F#e57373}' || echo '%{F#81c784}')

echo "%{F${color}}${icon}%{F-} %{F#81c784}%{T2}%{T-}%{F-}${price} ${preformat}${delta}%%{F-}"
