#!/usr/bin/env sh
type=$1
color=$2
icon=$3

info=$(curl -s https://api.coinmarketcap.com/v1/ticker/${type}/);
delta=$(echo "${info}" | grep _24h | grep -Po '[0-9\.\-\+]+' | tail -1);
price=$(echo "${info}" | grep price_usd | grep -Po '[0-9\.]+');
preformat=$([ $(echo "${delta}" | cut -b 1) == '-' ] && echo '%{F#e57373}' || echo '%{F#81c784}')

echo "%{F${color}}${icon}%{F-} %{F#81c784}%{T2}%{T-}%{F-}${price} ${preformat}${delta}%%{F-}"
