// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.20.3
// source: guild.proto

package guild

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceType int32

const (
	DeviceType_DEVICE_TYPE_ANY        DeviceType = 0
	DeviceType_DEVICE_TYPE_UNKNOWN    DeviceType = 1
	DeviceType_DEVICE_TYPE_CPU        DeviceType = 2
	DeviceType_DEVICE_TYPE_INTEGRATED DeviceType = 3
	DeviceType_DEVICE_TYPE_GPU        DeviceType = 4
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "DEVICE_TYPE_ANY",
		1: "DEVICE_TYPE_UNKNOWN",
		2: "DEVICE_TYPE_CPU",
		3: "DEVICE_TYPE_INTEGRATED",
		4: "DEVICE_TYPE_GPU",
	}
	DeviceType_value = map[string]int32{
		"DEVICE_TYPE_ANY":        0,
		"DEVICE_TYPE_UNKNOWN":    1,
		"DEVICE_TYPE_CPU":        2,
		"DEVICE_TYPE_INTEGRATED": 3,
		"DEVICE_TYPE_GPU":        4,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_guild_proto_enumTypes[0].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_guild_proto_enumTypes[0]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{0}
}

type DeviceBrand int32

const (
	DeviceBrand_DEVICE_BRAND_ANY     DeviceBrand = 0
	DeviceBrand_DEVICE_BRAND_UNKNOWN DeviceBrand = 1
	DeviceBrand_DEVICE_BRAND_INTEL   DeviceBrand = 2
	DeviceBrand_DEVICE_BRAND_NVIDIA  DeviceBrand = 3
	DeviceBrand_DEVICE_BRAND_AMD     DeviceBrand = 4
)

// Enum value maps for DeviceBrand.
var (
	DeviceBrand_name = map[int32]string{
		0: "DEVICE_BRAND_ANY",
		1: "DEVICE_BRAND_UNKNOWN",
		2: "DEVICE_BRAND_INTEL",
		3: "DEVICE_BRAND_NVIDIA",
		4: "DEVICE_BRAND_AMD",
	}
	DeviceBrand_value = map[string]int32{
		"DEVICE_BRAND_ANY":     0,
		"DEVICE_BRAND_UNKNOWN": 1,
		"DEVICE_BRAND_INTEL":   2,
		"DEVICE_BRAND_NVIDIA":  3,
		"DEVICE_BRAND_AMD":     4,
	}
)

func (x DeviceBrand) Enum() *DeviceBrand {
	p := new(DeviceBrand)
	*p = x
	return p
}

func (x DeviceBrand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceBrand) Descriptor() protoreflect.EnumDescriptor {
	return file_guild_proto_enumTypes[1].Descriptor()
}

func (DeviceBrand) Type() protoreflect.EnumType {
	return &file_guild_proto_enumTypes[1]
}

func (x DeviceBrand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceBrand.Descriptor instead.
func (DeviceBrand) EnumDescriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{1}
}

type Region int32

const (
	Region_REGION_ANY     Region = 0
	Region_REGION_UNKNOWN Region = 1
	Region_REGION_US_EAST Region = 2
)

// Enum value maps for Region.
var (
	Region_name = map[int32]string{
		0: "REGION_ANY",
		1: "REGION_UNKNOWN",
		2: "REGION_US_EAST",
	}
	Region_value = map[string]int32{
		"REGION_ANY":     0,
		"REGION_UNKNOWN": 1,
		"REGION_US_EAST": 2,
	}
)

func (x Region) Enum() *Region {
	p := new(Region)
	*p = x
	return p
}

func (x Region) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Region) Descriptor() protoreflect.EnumDescriptor {
	return file_guild_proto_enumTypes[2].Descriptor()
}

func (Region) Type() protoreflect.EnumType {
	return &file_guild_proto_enumTypes[2]
}

func (x Region) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Region.Descriptor instead.
func (Region) EnumDescriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{2}
}

type GuildQuest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier   string     `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Requirements *Resources `protobuf:"bytes,2,opt,name=requirements,proto3" json:"requirements,omitempty"`
}

func (x *GuildQuest) Reset() {
	*x = GuildQuest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildQuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildQuest) ProtoMessage() {}

func (x *GuildQuest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildQuest.ProtoReflect.Descriptor instead.
func (*GuildQuest) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{0}
}

func (x *GuildQuest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *GuildQuest) GetRequirements() *Resources {
	if x != nil {
		return x.Requirements
	}
	return nil
}

type GuildQuestAcknowledgement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accepted  bool   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Quest     string `protobuf:"bytes,2,opt,name=quest,proto3" json:"quest,omitempty"`
	Mercenary string `protobuf:"bytes,3,opt,name=mercenary,proto3" json:"mercenary,omitempty"`
}

func (x *GuildQuestAcknowledgement) Reset() {
	*x = GuildQuestAcknowledgement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildQuestAcknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildQuestAcknowledgement) ProtoMessage() {}

func (x *GuildQuestAcknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildQuestAcknowledgement.ProtoReflect.Descriptor instead.
func (*GuildQuestAcknowledgement) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{1}
}

func (x *GuildQuestAcknowledgement) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *GuildQuestAcknowledgement) GetQuest() string {
	if x != nil {
		return x.Quest
	}
	return ""
}

func (x *GuildQuestAcknowledgement) GetMercenary() string {
	if x != nil {
		return x.Mercenary
	}
	return ""
}

type Resources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Memory      uint64      `protobuf:"varint,1,opt,name=memory,proto3" json:"memory,omitempty"`
	DeviceType  DeviceType  `protobuf:"varint,2,opt,name=device_type,json=deviceType,proto3,enum=guild.DeviceType" json:"device_type,omitempty"`
	DeviceBrand DeviceBrand `protobuf:"varint,3,opt,name=device_brand,json=deviceBrand,proto3,enum=guild.DeviceBrand" json:"device_brand,omitempty"`
	Region      Region      `protobuf:"varint,4,opt,name=region,proto3,enum=guild.Region" json:"region,omitempty"`
}

func (x *Resources) Reset() {
	*x = Resources{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{2}
}

func (x *Resources) GetMemory() uint64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Resources) GetDeviceType() DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_DEVICE_TYPE_ANY
}

func (x *Resources) GetDeviceBrand() DeviceBrand {
	if x != nil {
		return x.DeviceBrand
	}
	return DeviceBrand_DEVICE_BRAND_ANY
}

func (x *Resources) GetRegion() Region {
	if x != nil {
		return x.Region
	}
	return Region_REGION_ANY
}

var File_guild_proto protoreflect.FileDescriptor

var file_guild_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67,
	0x75, 0x69, 0x6c, 0x64, 0x22, 0x62, 0x0a, 0x0a, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x12, 0x34, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x75, 0x69, 0x6c, 0x64,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x0c, 0x72, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x6b, 0x0a, 0x19, 0x47, 0x75, 0x69, 0x6c,
	0x64, 0x51, 0x75, 0x65, 0x73, 0x74, 0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x72, 0x63, 0x65,
	0x6e, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x72, 0x63,
	0x65, 0x6e, 0x61, 0x72, 0x79, 0x22, 0xb5, 0x01, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x32, 0x0a, 0x0b, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x11, 0x2e, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x35, 0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x2e, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x25, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x2a, 0x80, 0x01,
	0x0a, 0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f,
	0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x4e, 0x59, 0x10,
	0x00, 0x12, 0x17, 0x0a, 0x13, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x44, 0x45,
	0x56, 0x49, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x50, 0x55, 0x10, 0x02, 0x12,
	0x1a, 0x0a, 0x16, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49,
	0x4e, 0x54, 0x45, 0x47, 0x52, 0x41, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x44,
	0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x50, 0x55, 0x10, 0x04,
	0x2a, 0x84, 0x01, 0x0a, 0x0b, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x42, 0x72, 0x61, 0x6e, 0x64,
	0x12, 0x14, 0x0a, 0x10, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x42, 0x52, 0x41, 0x4e, 0x44,
	0x5f, 0x41, 0x4e, 0x59, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45,
	0x5f, 0x42, 0x52, 0x41, 0x4e, 0x44, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x01,
	0x12, 0x16, 0x0a, 0x12, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x42, 0x52, 0x41, 0x4e, 0x44,
	0x5f, 0x49, 0x4e, 0x54, 0x45, 0x4c, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x44, 0x45, 0x56, 0x49,
	0x43, 0x45, 0x5f, 0x42, 0x52, 0x41, 0x4e, 0x44, 0x5f, 0x4e, 0x56, 0x49, 0x44, 0x49, 0x41, 0x10,
	0x03, 0x12, 0x14, 0x0a, 0x10, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x42, 0x52, 0x41, 0x4e,
	0x44, 0x5f, 0x41, 0x4d, 0x44, 0x10, 0x04, 0x2a, 0x40, 0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x4e, 0x59, 0x10,
	0x00, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x5f,
	0x55, 0x53, 0x5f, 0x45, 0x41, 0x53, 0x54, 0x10, 0x02, 0x42, 0x19, 0x5a, 0x17, 0x64, 0x74, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x3b, 0x67,
	0x75, 0x69, 0x6c, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_guild_proto_rawDescOnce sync.Once
	file_guild_proto_rawDescData = file_guild_proto_rawDesc
)

func file_guild_proto_rawDescGZIP() []byte {
	file_guild_proto_rawDescOnce.Do(func() {
		file_guild_proto_rawDescData = protoimpl.X.CompressGZIP(file_guild_proto_rawDescData)
	})
	return file_guild_proto_rawDescData
}

var file_guild_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_guild_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_guild_proto_goTypes = []interface{}{
	(DeviceType)(0),                   // 0: guild.DeviceType
	(DeviceBrand)(0),                  // 1: guild.DeviceBrand
	(Region)(0),                       // 2: guild.Region
	(*GuildQuest)(nil),                // 3: guild.GuildQuest
	(*GuildQuestAcknowledgement)(nil), // 4: guild.GuildQuestAcknowledgement
	(*Resources)(nil),                 // 5: guild.Resources
}
var file_guild_proto_depIdxs = []int32{
	5, // 0: guild.GuildQuest.requirements:type_name -> guild.Resources
	0, // 1: guild.Resources.device_type:type_name -> guild.DeviceType
	1, // 2: guild.Resources.device_brand:type_name -> guild.DeviceBrand
	2, // 3: guild.Resources.region:type_name -> guild.Region
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_guild_proto_init() }
func file_guild_proto_init() {
	if File_guild_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_guild_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildQuest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildQuestAcknowledgement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resources); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_guild_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_guild_proto_goTypes,
		DependencyIndexes: file_guild_proto_depIdxs,
		EnumInfos:         file_guild_proto_enumTypes,
		MessageInfos:      file_guild_proto_msgTypes,
	}.Build()
	File_guild_proto = out.File
	file_guild_proto_rawDesc = nil
	file_guild_proto_goTypes = nil
	file_guild_proto_depIdxs = nil
}
