// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: receptionist.proto

package receptionist

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Receptionist_Active_FullMethodName = "/receptionist.Receptionist/Active"
)

// ReceptionistClient is the client API for Receptionist service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReceptionistClient interface {
	Active(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Acknowledgement, error)
}

type receptionistClient struct {
	cc grpc.ClientConnInterface
}

func NewReceptionistClient(cc grpc.ClientConnInterface) ReceptionistClient {
	return &receptionistClient{cc}
}

func (c *receptionistClient) Active(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Acknowledgement, error) {
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, Receptionist_Active_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReceptionistServer is the server API for Receptionist service.
// All implementations must embed UnimplementedReceptionistServer
// for forward compatibility
type ReceptionistServer interface {
	Active(context.Context, *Empty) (*Acknowledgement, error)
	mustEmbedUnimplementedReceptionistServer()
}

// UnimplementedReceptionistServer must be embedded to have forward compatible implementations.
type UnimplementedReceptionistServer struct {
}

func (UnimplementedReceptionistServer) Active(context.Context, *Empty) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Active not implemented")
}
func (UnimplementedReceptionistServer) mustEmbedUnimplementedReceptionistServer() {}

// UnsafeReceptionistServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReceptionistServer will
// result in compilation errors.
type UnsafeReceptionistServer interface {
	mustEmbedUnimplementedReceptionistServer()
}

func RegisterReceptionistServer(s grpc.ServiceRegistrar, srv ReceptionistServer) {
	s.RegisterService(&Receptionist_ServiceDesc, srv)
}

func _Receptionist_Active_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceptionistServer).Active(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Receptionist_Active_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceptionistServer).Active(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Receptionist_ServiceDesc is the grpc.ServiceDesc for Receptionist service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Receptionist_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "receptionist.Receptionist",
	HandlerType: (*ReceptionistServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Active",
			Handler:    _Receptionist_Active_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "receptionist.proto",
}
