image: nixos/latest
packages:
  - nixpkgs.git
  - nixpkgs.nix
repositories:
  nixpkgs: https://nixos.org/channels/nixos-19.09
sources:
  - https://git.sr.ht/~eadwu/boxpub
secrets:
  - e10dff8c-e095-457a-a450-2083b20dafa4
tasks:
  - setup: |
      sudo fallocate -l 4G swapfile
      sudo chmod 600 swapfile
      sudo mkswap swapfile
      sudo swapon swapfile
  - configure: |
      nix-env -iA cachix -f https://cachix.org/api/v1/install
      cachix use boxpub
  - build: |
      cd boxpub
      nix-build --no-out-link --max-jobs 1
      nix-build --no-out-link --max-jobs 1 | cachix push boxpub
